# SPDX-License-Identifier: GPL-2.0
# Makefile for Qualcomm Venus driver

meson-vdec-objs += vdec.o vdec_1.o esparser.o canvas.o h264.o vdec_hevc.o hevc.o

obj-$(CONFIG_VIDEO_AML_MESON_VDEC) += meson-vdec.o

